# lambda build environment

CC="clang"
CXX="clang++"

CFLAGS="-O2 -pipe -march=alderlake"
CXXFLAGS="${CFLAGS}"
LDFLAGS="-Wl,-O1"

PREFIX="/usr"

MAKEOPTS="-j6"

# Xorg-specific build environment (used by packages/xorg-libs and any
# X11-related package).

XORG_PREFIX="${PREFIX}"
XORG_CONFIG="--prefix=/usr --sysconfdir=/etc --localstatedir=/var --disable-static"
